// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWRwaU-ONx1zzDzBmE2k-ht2pGKYDdOaE',
    appId: '1:407806435442:web:e1553a393be1c8d6c7e2eb',
    messagingSenderId: '407806435442',
    projectId: 'trustnet-13147',
    authDomain: 'trustnet-13147.firebaseapp.com',
    storageBucket: 'trustnet-13147.firebasestorage.app',
    measurementId: 'G-FN4FRNYRMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNEC5uidQwPShWa7jfvSTuaeCPMt18P5A',
    appId: '1:407806435442:android:16b72c4348ed35f2c7e2eb',
    messagingSenderId: '407806435442',
    projectId: 'trustnet-13147',
    storageBucket: 'trustnet-13147.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEsD4I3nLbN5YM9QxhUuubvavKXP7vdAI',
    appId: '1:407806435442:ios:bbfb39d95f050c0dc7e2eb',
    messagingSenderId: '407806435442',
    projectId: 'trustnet-13147',
    storageBucket: 'trustnet-13147.firebasestorage.app',
    iosBundleId: 'com.example.trustnet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEsD4I3nLbN5YM9QxhUuubvavKXP7vdAI',
    appId: '1:407806435442:ios:bbfb39d95f050c0dc7e2eb',
    messagingSenderId: '407806435442',
    projectId: 'trustnet-13147',
    storageBucket: 'trustnet-13147.firebasestorage.app',
    iosBundleId: 'com.example.trustnet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWRwaU-ONx1zzDzBmE2k-ht2pGKYDdOaE',
    appId: '1:407806435442:web:c0241f80ed19d305c7e2eb',
    messagingSenderId: '407806435442',
    projectId: 'trustnet-13147',
    authDomain: 'trustnet-13147.firebaseapp.com',
    storageBucket: 'trustnet-13147.firebasestorage.app',
    measurementId: 'G-K11Q0RP033',
  );
}
